name: listandtable
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/myimage.jpg
    - assets/icons/google.svg
    - assets/icons/facebook.svg
    - assets/icons/discord.svg
    - assets/loginpage.jpg